spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: yejin

  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성/수정
    properties:
      hibernate:
        format_sql: true
        show_sql: true
